DELETE FROM BILLINGINFORMATIONENTITY;
DELETE FROM CANCIONENTITY;
DELETE FROM CARRITODECOMPRASENTITY;
DELETE FROM COMENTARIOENTITY;
DELETE FROM ENVIOENTITY;
DELETE FROM MEDIODEPAGOENTITY;
DELETE FROM TRANSACCIONENTITY;
DELETE FROM VINILOENTITY_CARRITODECOMPRASENTITY;
DELETE FROM VINILOENTITY_WISHLISTENTITY;
DELETE FROM WISHLISTENTITY;
DELETE FROM VINILOENTITY;
DELETE FROM USUARIOENTITY;
DELETE FROM VINILOENTITY;
DELETE FROM USUARIOENTITY;


INSERT INTO USUARIOENTITY (id, calificacion, CONTRASENHA, direccion, email, imagen, nombre, rol,username) values ( 1, 5, 'AAA','Calle 2 No. 22-22', 'andres@hotmail.com', 'https://i.ytimg.com/vi/wAY8mTWlna0/hqdefault.jpg' , 'Andres', 'ADMIN' ,'linkhl' );
INSERT INTO USUARIOENTITY (id, calificacion, CONTRASENHA, direccion, email, imagen, nombre, rol,username) values ( 2, 5, 'BBB', 'Calle 21 No. 1-20', 'camilo@hotmail.com', 'https://images.pexels.com/photos/213117/pexels-photo-213117.jpeg?cs=srgb&dl=adult-bald-beard-213117.jpg&fm=jpg', 'Camilo', 'USUARIO' ,'rembrandtx' );
INSERT INTO USUARIOENTITY (id, calificacion, CONTRASENHA, direccion, email, imagen, nombre, rol,username) values ( 3, 5, 'CCC', 'Calle 1 f bis No. 19-79', 'isabella@hotmail.com', 'https://ak2.picdn.net/shutterstock/videos/10547162/thumb/1.jpg' ,  'Isabela', 'ADMIN' ,'li.forero' );
INSERT INTO USUARIOENTITY (id, calificacion, CONTRASENHA, direccion, email, imagen, nombre, rol,username) values ( 4, 5, 'DDD', 'Calle 22d No. 90-35', 'sebastian@hotmail.com', 'https://images.pexels.com/photos/213117/pexels-photo-213117.jpeg?cs=srgb&dl=adult-bald-beard-213117.jpg&fm=jpg',  'sebastian', 'USUARIO' ,'sebastian' );
INSERT INTO USUARIOENTITY (id, calificacion, CONTRASENHA, direccion, email, imagen, nombre, rol,username) values ( 5, 5, 'EEE', 'Calle 135 No.20-5', 'kevin@hotmail.com', 'https://images.pexels.com/photos/213117/pexels-photo-213117.jpeg?cs=srgb&dl=adult-bald-beard-213117.jpg&fm=jpg', 'kevin', 'USUARIO' ,'kevin');

INSERT INTO BILLINGINFORMATIONENTITY (ID, CUENTAAHORRO, RECIEVED, SPENT, USUARIO_ID) VALUES (1, '1234567891', 1000, 1000, 1);
INSERT INTO BILLINGINFORMATIONENTITY (ID, CUENTAAHORRO, RECIEVED, SPENT, USUARIO_ID) VALUES (2, '2345678912', 1000, 1000, 2);
INSERT INTO BILLINGINFORMATIONENTITY (ID, CUENTAAHORRO, RECIEVED, SPENT, USUARIO_ID) VALUES (3, '3456789123', 1000, 1000, 3);
INSERT INTO BILLINGINFORMATIONENTITY (ID, CUENTAAHORRO, RECIEVED, SPENT, USUARIO_ID) VALUES (4, '4567891234', 1000, 1000, 4);
INSERT INTO BILLINGINFORMATIONENTITY (ID, CUENTAAHORRO, RECIEVED, SPENT, USUARIO_ID) VALUES (5, '5678912345', 1000, 1000, 5);

INSERT INTO WISHLISTENTITY(ID, COSTO, USUARIO_ID) VALUES (1, 0, 1);
INSERT INTO WISHLISTENTITY(ID, COSTO, USUARIO_ID) VALUES (2, 0, 2);
INSERT INTO WISHLISTENTITY(ID, COSTO, USUARIO_ID) VALUES (3, 0, 3);
INSERT INTO WISHLISTENTITY(ID, COSTO, USUARIO_ID) VALUES (4, 0, 4);
INSERT INTO WISHLISTENTITY(ID, COSTO, USUARIO_ID) VALUES (5, 0, 5);

INSERT INTO CARRITODECOMPRASENTITY(ID, TOTALCOST, USUARIO_ID) VALUES (1, 0, 1);
INSERT INTO CARRITODECOMPRASENTITY(ID, TOTALCOST, USUARIO_ID) VALUES (2, 0, 2);
INSERT INTO CARRITODECOMPRASENTITY(ID, TOTALCOST, USUARIO_ID) VALUES (3, 0, 3);
INSERT INTO CARRITODECOMPRASENTITY(ID, TOTALCOST, USUARIO_ID) VALUES (4, 0, 4);
INSERT INTO CARRITODECOMPRASENTITY(ID, TOTALCOST, USUARIO_ID) VALUES (5, 0, 5);

INSERT INTO MEDIODEPAGOENTITY (ID, CVC, FECHAVENCIMIENTO, IMAGEN, NAME, NUMERO, NUMEROVERIFICACION, BILLING_ID) VALUES ( 1,'123' ,'2019-12-12' ,'' ,'VISA' ,12345678,12345678 ,1);
INSERT INTO MEDIODEPAGOENTITY (ID, CVC, FECHAVENCIMIENTO, IMAGEN, NAME, NUMERO, NUMEROVERIFICACION, BILLING_ID) VALUES ( 2,'456' ,'2019-12-12' ,'' ,'MASTERCARD' ,23456789 ,23456789 ,2);
INSERT INTO MEDIODEPAGOENTITY (ID, CVC, FECHAVENCIMIENTO, IMAGEN, NAME, NUMERO, NUMEROVERIFICACION, BILLING_ID) VALUES ( 3,'789' ,'2019-12-12' ,'' ,'AMERICAN EXPRESS' ,34567890 ,34567890,3);
INSERT INTO MEDIODEPAGOENTITY (ID, CVC, FECHAVENCIMIENTO, IMAGEN, NAME, NUMERO, NUMEROVERIFICACION, BILLING_ID) VALUES ( 4,'012' ,'2019-12-12' ,'' ,'VISA' ,456789012 ,456789012,4);
INSERT INTO MEDIODEPAGOENTITY (ID, CVC, FECHAVENCIMIENTO, IMAGEN, NAME, NUMERO, NUMEROVERIFICACION, BILLING_ID) VALUES ( 5,'345' ,'2019-12-12' ,'' ,'MASTERCAD' ,56789012 ,56789012 ,5);

INSERT INTO VINILOENTITY(ID, ARTISTA, CALIFICACION, CATEGORIA, FECHALANZAMIENTO, INFORMACIONADICIONAL,NOMBRE, PRECIO, PREVIEWURI, PRODUCTORA, USUARIO_ID) VALUES (1, 'MO', 5, 'Pop', '2018-01-01', 'No esta abierto.', 'Freak Show', 40000, 'http://www.musicapopular.cl/biblioteca/wp-content/uploads/2015/11/viniolochileno.jpg', 'Music Records', 1);
INSERT INTO VINILOENTITY(ID, ARTISTA, CALIFICACION, CATEGORIA, FECHALANZAMIENTO, INFORMACIONADICIONAL,NOMBRE, PRECIO, PREVIEWURI, PRODUCTORA, USUARIO_ID) VALUES (2, 'QUEEN', 5, 'Rock', '2017-01-01',  'No est abierto.', 'Bohemian Rhapsody', 50000, 'https://www.vichaunter.org/wp-content/uploads/14433900-registro-de-lp-de-vinilo-negro-en-el-disco-disco-aislado-en-blanco.jpg', 'Music Records', 2);